name: Python CI

on:
  push:
    branches:
      - main
      # - "feature/**"  # CI will run on pushes to the main branch and feature branches
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Check out the repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests
      - name: Run tests
        run: |
          pytest

      # (Optional) Check code formatting with flake8
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .

      # (Optional) Check code coverage
      - name: Coverage with pytest-cov
        run: |
          pip install pytest-cov
          pytest --cov=your_package_name

